apiVersion: v1
kind: pod
metadata:
  name: nginx
  label: 
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:latest 
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80