apiVersion: v1
kind: pod
metadata:
  name: nginx
  label: 
    app: nginx
spec:
  containers:
  - name: flask
    image: stratcastor/duo-deploy-flask:latest # Dockerhub
    ports:
    - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500